openapi: 3.1.0
info:
  title: Mail History API
  description: |
    REST API endpoints for Mail History
  version: 1.0.0
servers:
  - url: http://localhost:8089/api/v1/openerpmailsender
    description: Development server
paths:
  /mail-histories:
    get:
      tags:
        - MailHistory
      summary: Fetch all mail history from database
      operationId: fetchMailHistories
      security:
        - oAuth:
            - read:mail_history
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/direction'
        - $ref: '#/components/parameters/attribute'
      responses:
        200:
          description: successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponseDto'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponseDto'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponseDto'
  /mail-histories/search:
    get:
      tags:
        - MailHistory
      summary: Fetch all mail history matching a keyword
      operationId: fetchMailHistoryByKeyword
      security:
        - oAuth:
            - read:mail_history
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/direction'
        - $ref: '#/components/parameters/attribute'
        - $ref: '#/components/parameters/keyword'
      responses:
        200:
          description: successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponseDto'
        400:
          description: bad operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponseDto'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponseDto'
  /mail-histories/{mailHistoryId}:
    get:
      tags:
        - MailHistory
      summary: Return mail history fetched from database with provided id
      operationId: fetchMailHistoryById
      security:
        - oAuth:
            - read:mail_history
      parameters:
        - $ref: '#/components/parameters/mailHistoryId'
      responses:
        200:
          description: successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponseDto'
        404:
          description: not found operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponseDto'
components:
  parameters:
    mailHistoryId:
      name: mailHistoryId
      in: path
      required: true
      schema:
        type: string
    page:
      name: page
      in: query
      required: true
      schema:
        type: integer
    size:
      name: size
      in: query
      required: true
      schema:
        type: integer
    direction:
      name: direction
      in: query
      required: true
      schema:
        type: string
        enum:
          - ASC
          - DSC
    attribute:
      name: attribute
      in: query
      required: true
      schema:
        type: string
    keyword:
      name: keyword
      in: query
      required: true
      schema:
        type: string
  schemas:
    ValidationErrorDto:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
        message:
          type: string
    ApiResponseDto:
      type: object
      required:
        - timestamp
        - code
        - status
        - success
      properties:
        timestamp:
          type: string
        code:
          type: integer
          format: int32
        status:
          type: string
        success:
          type: boolean
    ApiSuccessResponseDto:
      allOf:
        - $ref: '#/components/schemas/ApiResponseDto'
        - type: object
          properties:
            message:
              type: string
            data:
              type: object
              additionalProperties:
                type: object
    ApiErrorResponseDto:
      allOf:
        - $ref: '#/components/schemas/ApiResponseDto'
        - type: object
          required:
            - reason
            - path
            - trackId
          properties:
            reason:
              type: string
            developerMessage:
              type: string
            path:
              type: string
            trackId:
              type: string
              format: uuid
            error:
              type: array
              items:
                $ref: '#/components/schemas/ValidationErrorDto'